/acquisition_left:
  ros__parameters:
    serialNumber: "KE0220040188"
    exposureTime: 400 #xx
    autoExposure: True # Mporoun na mpoun kai True kai exposureTime, ta exw kanei handle sthn
    # klash ths cameras, ola komple
    customAutoexposure: False # an autoExposure==True kai custom==True tote yperisxyei to custom
    expectedGrayValue: 50
    ROIx: 1280
    ROIy: 1024
    orientation: "left"
    log_photos: False


/acquisition_right:
  ros__parameters:
    serialNumber: "KE0220030138"
    exposureTime: 400 #xx
    autoExposure: True
    customAutoexposure: False # an autoExposure==True kai custom==True tote yperisxyei to custom
    expectedGrayValue: 50
    ROIx: 1280
    ROIy: 1024
    orientation: "right"
    log_photos: False


/slam:
  ros__parameters:
    velocity_estimation_frequency: 40

    # This sets the mode of operation. Set true for slam and false for localization
    mapping_mode: False
    track_map: "/Tracks/Acceleration.txt"
    dynamic_accel_map: False

    # Defines the starting position of the car
    starting_position: [ -2.01, 0.0, 0.0 ]
    starting_position_covariance: [ 0.5, 0.1, 0.01 ]

    # The max distance perception measurements are accepted
    perception_range: 13.0

    # After how many time steps the optimization algorithm would be executed
    optimization_interval: 4

    # The max distance at which two cones would be associated
    association_threshold: 1.9
    min_observations: 4

    # iSAM parameters
    relinearize_threshold: 0.1
    relinearize_skip: 1

    # Big orange cones for starting/finish line
    left_orange: [75.0, -2.5]
    right_orange: [75.0, 2.5]

    lap_counter_cooldown: 10

    logger: true


/saltas:
  ros__parameters:
      velocity_estimation_frequency: 40   # Hz
      perception_frequency: 10            # Hz


/velocity_estimation:
  ros__parameters:
    frequency: 40                         # Hz

    initial_state_vector: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    initial_state_covariance: [1.0e-3,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0, 1.0e-3,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0, 1.0e-3,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0, 1.0e-3,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0, 1.0e-3,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0, 1.0e-3]

    process_noise_covariance: [7.0e-3,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0, 8.0e-3,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0, 5.0e-6,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0, 5.0e-4,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0, 3.0e-4,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0, 1.0e-4]

    measurement_noise_covariance: [   0.30,-13.0e-4,      0.0,       0.0,       0.0,  0.0,   0.0,
                                   -13.0e-4,   0.024,      0.0,       0.0,       0.0,  0.0,   0.0,
                                        0.0,     0.0, 1.22e-06,       0.0,       0.0,  0.0,   0.0,
                                        0.0,     0.0,      0.0,     0.032,-7.612e-05,  0.0,   0.0,
                                        0.0,     0.0,      0.0,-7.612e-05,     0.051,  0.0,   0.0,
                                        0.0,     0.0,      0.0,       0.0,       0.0, 60.0,   0.0,
                                        0.0,     0.0,      0.0,       0.0,       0.0,  0.0,  50.0]

    # Sensor Positions
    vectornav-vn-200:
      # x: 0.6461                 # [m]
      # x: 0.6578 #0.4278+0.32
      x: 0.7478
      y: 0.00                   # [m]
      pitch: -2.560461679695934        # [deg]
      roll: 0.8152647739704287            # [deg]
    vectornav-vn-300:
      x: 0.4278                 # [m]
      y: 0.00                   # [m]
      pitch: 10.002063491559252           # [deg]
      roll: 0.8380131114263331           # [deg]
    
    # Car characteristics
    wheel_radius: 0.2054        # [m]
    front_axle: 0.76            # [m]
    rear_axle: 0.89             # [m]


/pure_pursuit:
  ros__parameters:
    discipline: "EBS_Test"
    #model
    mass: 193.5
    gravitational_acceleration: 9.81
    wheelbase: 1.59
    weight_distribution: 0.467
    h_cog: 0.27
    air_density: 1.225
    Cd*A: 2.0
    Cl*A: 7.0
    gear_ratio: 3.9
    wheel_radius: 0.2054
    efficiency: 0.85
    Fz_0: 1112.0554070627252
    max_positive_torque: 70.0              #EDIT BEFORE
    max_negative_torque: -100.0             #EDIT BEFORE
    minimum_weight_distribution_rear: 1.0  
    c_tire: 0.66

    #Pure Pursuit
    ld_min: 6.0                             #EDIT BEFORE
    ld_max: 14.0                             #EDIT BEFORE
    v_min: 3.0                              #EDIT BEFORE
    v_max: 14.0                             #EDIT BEFORE
    emergency_factor: 0.75
    emergency_threshold: 5.0
    safety_factor: 0.85
    max_speed: 11.11                        #EDIT BEFORE 14m/s = 50.4km/h, 40km/h = 11.111m/s
    dt: 0.025
    safe_speed_to_break: 0.1
    braking_distance: 50.0
    max_steering: 25.0
    max_torque_difference: 2.0
    dynamic_vp: True
    motor_control: False

    #PID
    kp: 1000
    ki: 50
    kd: 0
    PID_max_output: 3000
    Integral_max_output: 2000
    spline_resolution_per_meter: 10
    total_laps: 2                           #CHECK BEFORE

/mpc: #same as accel
  ros__parameters:
    simulation: false
    mission: "accel"
    regen: true
    total_laps: 1
    v_limit: 17.5
    node_freq: 40.0
    s_interval: 0.2
    distance_safe: 1.0
    emergency_forward: 1.0
    F_init: 300.0
    F_max: 500.0
    F_min: -500.0
    s_space_max: 0.5
    s_space_min: 0.1  