/inspection:
  ros__parameters:
    mode: 'bench' #'inspection' or 'bench'
    control_mode: 'velocity'
    max_torque: 3000.0
    min_torque: 0.0
    torque_step: 200.0
    # [ 24.0mm,       (23.96173 + 27.01392) / 2 = 25.4878 deg = 0.4448rad],
    max_steering: 0.448
    # [-24.0mm,       (-27.01392 -23.96173) / 2 = -25.4878 deg = -0.4448rad]
    min_steering: -0.448
    #1 degree = 0.0174 rad
    steering_step: 0.084
    max_press: 25.0
    min_press: 0.0
    press_step: 1.0
    publish_frequency: 40.0
    kp: -2500.0
    kd: 0.0
    ki: 0.0
    dt: 0.01
    minvel: -25000.0
    maxvel: 25000.0
    motor_by_function: False   # True or False
    motor_function: 'square'    # 'sine' or 'square'
    motor_frequency: 0.5     # float Hz
    steer_by_function: False  # True or False
    steer_function: 'square'    # 'sine' or 'square'
    steer_frequency: 0.5     # float Hz
    brake_by_function: False   # True or False
    brake_function: 'square'    # 'sine' or 'square'
    brake_frequency: 0.5     # float Hz
