lifecycle_manager:
  ros__parameters:
    managing_node_list: ["acquisition_left", "inference", "saltas", "velocity_estimation", "path_planning", "slam", "pure_pursuit", "mpc", "inspection"]
    heartbeat_timeout_period: 1000  #heartbeat period in milliseconds
    heartbeat_frequency:  5 # in Hz
    resurrect_failed_nodes: False
    heartbeat_failures_before_resurrection: 3
    
    # managing_node_list: ["saltas", "acquisition_left", "acquisition_right", 
    # "inference", "velocity_estimation", "slam", "path_planning",
    # "pure_pursuit", "mpc",]

    # Uncomment for inspection mission
    # managing_node_list: ["inspection"]
  
  # The managing node list parameter should have all the nodes that are managed by the manager.
  # Whichever node is not needed in the end due to a specific mission happening is handled inside
  # the manager itself.