acquisition_left:
  ros__parameters:
    serialNumber: "KE0220030137"
    exposureTime: 10000
    ROIx: 1280
    ROIy: 1024
    orientation: "left"

acquisition_right:
  ros__parameters:
    serialNumber: "KE0220040196"
    exposureTime: 10000
    ROIx: 1280
    ROIy: 1024
    orientation: "right"

acquisition_center:
  ros__parameters:
    serialNumber: "KE0220030138"
    exposureTime: 10000
    ROIx: 1280
    ROIy: 1024
    orientation: "center"