(cl:in-package fssim_common-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRAG_FORCE-VAL
          DRAG_FORCE
          DELTA-VAL
          DELTA
          DC-VAL
          DC
          FRONT_LEFT_STEERING_ANGLE-VAL
          FRONT_LEFT_STEERING_ANGLE
          FRONT_RIGHT_STEERING_ANGLE-VAL
          FRONT_RIGHT_STEERING_ANGLE
          DELTA_MEASURED-VAL
          DELTA_MEASURED
          VX-VAL
          VX
          VY-VAL
          VY
          R-VAL
          R
          TORQUE_OK-VAL
          TORQUE_OK
          ALPHA_F-VAL
          ALPHA_F
          ALPHA_F_L-VAL
          ALPHA_F_L
          ALPHA_F_R-VAL
          ALPHA_F_R
          ALPHA_R_L-VAL
          ALPHA_R_L
          ALPHA_R-VAL
          ALPHA_R
          ALPHA_R_R-VAL
          ALPHA_R_R
          FY_F-VAL
          FY_F
          FY_F_L-VAL
          FY_F_L
          FY_F_R-VAL
          FY_F_R
          FY_R-VAL
          FY_R
          FY_R_L-VAL
          FY_R_L
          FY_R_R-VAL
          FY_R_R
          FX-VAL
          FX
))