canbus:
  can_interface:
    ros__parameters:
      # Configure Port
      port: '/dev/ttyACM0'
      baudrate: 115200
      timeout: 0.1

      read_frequency: 50

      # Sensor Configuration - Incoming Messages
      enabled_sensors: ['front_halls', 'rear_halls', 'steering', 'brakes']
      # outgoing_messages: ['simple_pub']