# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fssim_common/ResState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ResState(genpy.Message):
  _md5sum = "2c68d942044efe0714c25879acd65327"
  _type = "fssim_common/ResState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# State of the three buttons on the RES
bool emergency 					# 0 = OK, 1 = Emergency
bool on_off_switch 				# 0 = 0, 1 = 1 (Comments couldn't be more helpful :p )
bool push_button 				# 1 = pressed
# RES will trigger emergency 200ms after this becomes 1 (unless communication is recovered)
bool communication_interrupted 	# 0 = OK, 1 = Interrupted
"""
  __slots__ = ['emergency','on_off_switch','push_button','communication_interrupted']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       emergency,on_off_switch,push_button,communication_interrupted

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ResState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.emergency is None:
        self.emergency = False
      if self.on_off_switch is None:
        self.on_off_switch = False
      if self.push_button is None:
        self.push_button = False
      if self.communication_interrupted is None:
        self.communication_interrupted = False
    else:
      self.emergency = False
      self.on_off_switch = False
      self.push_button = False
      self.communication_interrupted = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.emergency, _x.on_off_switch, _x.push_button, _x.communication_interrupted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.emergency, _x.on_off_switch, _x.push_button, _x.communication_interrupted,) = _get_struct_4B().unpack(str[start:end])
      self.emergency = bool(self.emergency)
      self.on_off_switch = bool(self.on_off_switch)
      self.push_button = bool(self.push_button)
      self.communication_interrupted = bool(self.communication_interrupted)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.emergency, _x.on_off_switch, _x.push_button, _x.communication_interrupted))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.emergency, _x.on_off_switch, _x.push_button, _x.communication_interrupted,) = _get_struct_4B().unpack(str[start:end])
      self.emergency = bool(self.emergency)
      self.on_off_switch = bool(self.on_off_switch)
      self.push_button = bool(self.push_button)
      self.communication_interrupted = bool(self.communication_interrupted)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
