# Incoming Messages
front_halls:
  id: 0x310
  topic: 'front_hall_sensors'
  msg_type: 'hall_msg'
  parser: 'hall_parser'

rear_halls:
  id: 0x4D1
  topic: 'rear_hall_sensors'
  msg_type: 'hall_msg'
  parser: 'hall_parser'

steering:
  id: 0x4D2
  topic: 'steering_angle'
  msg_type: 'steering_msg'
  parser: 'steering_parser'

brakes:
  id: 0x301
  topic: 'brake_pressure'
  msg_type: 'brake_pressure_msg'
  parser: 'brakes_parser'

test_hall:
  id: 0x305
  topic: 'wheel_encoders'
  msg_type: 'sim_halls'
  parser: 'hall_callback'

mission_selection:
  id: 0x500
  topic: 'mission_selection'
  msg_type: 'mission'
  parser: 'mission_selection'

autonomous_status:
  id: 0x501
  topic: 'as_status'
  msg_type: 'autonomous_status'
  parser: 'autonomous_status'

# Outgoing Messages
system_state:
  id: 0x00
  topic: 'p23_status/system_state'
  msg_type: 'system_state'
  callback: 'system_state'

vehicle_variables:
  id: 0x01
  topic: 'p23_status/vehicle_variables'
  msg_type: 'vehicle_variables'
  callback: 'vehicle_variables'

control_command:
  id: 0x02
  topic: 'p23_status/control_command'
  msg_type: 'control_command'
  callback: 'control_command'