velocity_estimation_node:
  ros__parameters:
    frequency: 40               # [Hz]

    initial_state_vector: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    initial_state_covariance: [1.0e-3,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0, 1.0e-3,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0, 1.0e-3,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0, 1.0e-3,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0, 1.0e-3,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0, 1.0e-3]
    
    process_noise_covariance: [7.0e-3,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0, 8.0e-3,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0, 5.0e-6,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0, 5.0e-4,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0, 3.0e-4,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0, 1.0e-4]

    measurement_noise_covariance: [   0.030,-13.0e-4,      0.0,       0.0,       0.0,  0.0,   0.0,
                                   -13.0e-4,   0.024,      0.0,       0.0,       0.0,  0.0,   0.0,
                                        0.0,     0.0, 1.22e-06,       0.0,       0.0,  0.0,   0.0,
                                        0.0,     0.0,      0.0,     0.032,-7.612e-05,  0.0,   0.0,
                                        0.0,     0.0,      0.0,-7.612e-05,     0.051,  0.0,   0.0,
                                        0.0,     0.0,      0.0,       0.0,       0.0, 60.0,   0.0,
                                        0.0,     0.0,      0.0,       0.0,       0.0,  0.0, 180.0]

    # Sensor Positions
    vectornav-vn-200:
      # x: 0.6461                 # [m]
      x: 0.72                 # [m]
      y: 0.00                   # [m]
      pitch: 0.849             # [deg]
      roll: 12.8364             # [deg]
    vectornav-vn-300:
      x: 0.4278                 # [m]
      y: 0.00                   # [m]
      pitch: 11.08213           # [deg]
      roll: 0.05579             # [deg]
    
    # Car characteristics
    wheel_radius: 0.1995        # [m]
    front_axle: 0.76            # [m]
    rear_axle: 0.89             # [m]