velocity_estimation_node:
  ros__parameters:
    frequency: 50               # [Hz]

    initial_state_vector: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    initial_state_covariance: [1.0e-3,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0, 1.0e-3,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0, 1.0e-3,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0, 1.0e-3,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0, 1.0e-3,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0, 1.0e-3]
    
    process_noise_covariance: [7.0e-4,    0.0,    0.0,    0.0,    0.0,    0.0,
                                  0.0, 8.0e-4,    0.0,    0.0,    0.0,    0.0,
                                  0.0,    0.0, 5.0e-6,    0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0, 5.0e-4,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0, 3.0e-4,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0, 1.0e-4]

    measurement_noise_covariance: [   0.091,-13.0e-4,      0.0,       0.0,       0.0,  0.0,  0.0,
                                   -13.0e-4,   0.064,      0.0,       0.0,       0.0,  0.0,  0.0,
                                        0.0,     0.0, 1.22e-06,       0.0,       0.0,  0.0,  0.0,
                                        0.0,     0.0,      0.0,     0.032,-7.612e-05,  0.0,  0.0,
                                        0.0,     0.0,      0.0,-7.612e-05,     0.051,  0.0,  0.0,
                                        0.0,     0.0,      0.0,       0.0,       0.0, 20.0,  0.0,
                                        0.0,     0.0,      0.0,       0.0,       0.0,  0.0, 20.0]

    # Sensor Positions
    vectornav-vn-200:
      x: 0.49                   # [m]
      y: 0.00                   # [m]
      roll: -0.528              # [deg]
      pitch: -4.140             # [deg]
    vectornav-vn-300:
      x: 0.18                   # [m]
      y: 0.00                   # [m]
      roll: -1.440              # [deg]
      pitch: 2.192              # [deg]
    
    # Car characteristics
    wheel_radius: 0.1995        # [m]
    front_axle: 0.76            # [m]
    rear_axle: 0.89             # [m]