% FORCESNLPsolver - a fast solver generated by FORCESPRO v6.3.0
%
%   OUTPUT = FORCESNLPsolver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.xinit - matrix of size [8x1]
%       PARAMS.x0 - matrix of size [300x1]
%       PARAMS.all_parameters - matrix of size [120x1]
%       PARAMS.reinitialize - scalar
%       PARAMS.num_of_threads - scalar
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.x01 - column vector of length 10
%       OUTPUT.x02 - column vector of length 10
%       OUTPUT.x03 - column vector of length 10
%       OUTPUT.x04 - column vector of length 10
%       OUTPUT.x05 - column vector of length 10
%       OUTPUT.x06 - column vector of length 10
%       OUTPUT.x07 - column vector of length 10
%       OUTPUT.x08 - column vector of length 10
%       OUTPUT.x09 - column vector of length 10
%       OUTPUT.x10 - column vector of length 10
%       OUTPUT.x11 - column vector of length 10
%       OUTPUT.x12 - column vector of length 10
%       OUTPUT.x13 - column vector of length 10
%       OUTPUT.x14 - column vector of length 10
%       OUTPUT.x15 - column vector of length 10
%       OUTPUT.x16 - column vector of length 10
%       OUTPUT.x17 - column vector of length 10
%       OUTPUT.x18 - column vector of length 10
%       OUTPUT.x19 - column vector of length 10
%       OUTPUT.x20 - column vector of length 10
%       OUTPUT.x21 - column vector of length 10
%       OUTPUT.x22 - column vector of length 10
%       OUTPUT.x23 - column vector of length 10
%       OUTPUT.x24 - column vector of length 10
%       OUTPUT.x25 - column vector of length 10
%       OUTPUT.x26 - column vector of length 10
%       OUTPUT.x27 - column vector of length 10
%       OUTPUT.x28 - column vector of length 10
%       OUTPUT.x29 - column vector of length 10
%       OUTPUT.x30 - column vector of length 10
%
%   [OUTPUT, EXITFLAG] = FORCESNLPsolver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%      -8 - QP solver failed. The QP solver failed to converge. Check your variable bounds and inequality constraints. Consider scaling your problem.
%     -98 - Thread error
%     -99 - Locking mechanism error
%    -100 - License error
%    -101 - Insufficient number of internal memory instances
%    -102 - Number of threads larger than specified
%
%   [OUTPUT, EXITFLAG, INFO] = FORCESNLPsolver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it - scalar: iteration number
%       INFO.res_eq - scalar: inf-norm of equality constraint residuals
%       INFO.rsnorm - scalar: norm of stationarity condition
%       INFO.pobj - scalar: primal objective
%       INFO.solvetime - scalar: total solve time
%       INFO.fevalstime - scalar: time spent in function evaluations
%       INFO.QPtime - scalar: time spent solving inner QPs
%       INFO.QPit - scalar: iterations spent in solving inner QPs
%       INFO.QPexitflag - scalar: last exitflag of inner QP solver
%       INFO.solver_id - column vector of length 8: solver ID of FORCESPRO solver
%
% See also COPYING
