lifecycle_acquisition_left:
  ros__parameters:
    serialNumber: "KE0220030137"
    exposureTime: 40000
    autoExposure: False # Mporoun na mpoun kai True kai exposureTime, ta exw kanei handle sthn
    # klash ths cameras, ola komple
    expectedGrayValue: 50
    ROIx: 1280
    ROIy: 1024
    orientation: "left"

lifecycle_acquisition_right:
  ros__parameters:
    serialNumber: "KE0220040196"
    exposureTime: 40000
    autoExposure: False
    expectedGrayValue: 50
    ROIx: 1280
    ROIy: 1024
    orientation: "right"

lifecycle_acquisition_center:
  ros__parameters:
    serialNumber: "KE0220030138"
    exposureTime: 1500
    autoExposure: False
    expectedGrayValue: 50
    ROIx: 1280
    ROIy: 1024
    orientation: "center"

/acquisition_left:
  ros__parameters:
    serialNumber: "KE0220040188"
    exposureTime: 2000 #xx
    autoExposure: True # Mporoun na mpoun kai True kai exposureTime, ta exw kanei handle sthn
    # klash ths cameras, ola komple
    expectedGrayValue: 50
    ROIx: 1280
    ROIy: 1024
    orientation: "left"
    log_photos: True


/acquisition_right:
  ros__parameters:
    serialNumber: "KE0220030138"
    exposureTime: 2000 #xx
    autoExposure: True
    expectedGrayValue: 50
    ROIx: 1280
    ROIy: 1024
    orientation: "right"
    log_photos: True