acquisition_left:
  ros__parameters:
    serialNumber: "KE0220040188"
    exposureTime: 1000.0
    autoExposure: False # Mporoun na mpoun kai True kai exposureTime, ta exw kanei handle sthn
    # klash ths cameras, ola komple
    expectedGrayValue: 50.0
    ROIx: 1280.0
    ROIy: 1024.0
    orientation: "left"

# acquisition_right:
#   ros__parameters:
#     serialNumber: "KE0220030138"
#     exposureTime: 1000.0
#     autoExposure: False
#     expectedGrayValue: 50.0
#     ROIx: 1280.0
#     ROIy: 1024.0
#     orientation: "right"

# acquisition_center:
#   ros__parameters:
#     serialNumber: "KE0220030138"
#     exposureTime: 1500
#     autoExposure: False
#     expectedGrayValue: 50
#     ROIx: 1280
#     ROIy: 1024
#     orientation: "center"

    # Na vazete double times (float, dhladh gia osous den kseroun, kinhths ypodiastolhs kai OXI integer, giati komplarei to ROS)
