slam_node:
  ros__parameters:
    
    small_dist_threshold: 1.5
    large_dist_threshold: 2.0

    dt: 0.02

    left_orange: [6.0, -3.0]
    right_orange: [6.0, 3.0]

    prior_pose_noise: [0.03, 0.03, 0.01]

    range_limit: 12.0

    weight: 0.75

    cooldown_max: 10