slam_node:
  ros__parameters:
    # This sets the mode of operation. Set true for slam and false for 
    # localization
    mapping_mode: true
    track_map: "/test_tracks/skidpad_new.txt"

    # Defines the starting position of the car
    starting_position: [ -8.2, 0.0, 0.0 ]
    starting_position_covariance: [ 0.5, 0.1, 0.01 ]

    # The max distance perception measurements are accepted
    perception_range: 12.0

    # After how many time steps the optimization algorithm would be executed
    optimization_interval: 20

    # The max distance at which two cones would be associated
    association_threshold: 1.9

    # iSAM parameters
    relinearize_threshold: 0.1
    relinearize_skip: 1

    odometry_covariance_weight: 10.0
    perception_covariance_weight: 0.01

    # Big orange cones for starting/finish line
    left_orange: [0.0, -2.5]
    right_orange: [0.0, 2.5]

    lap_counter_cooldown: 10

    logger: true
    velocity_estimation_frequency: 40