l_mpc_new:
  ros__parameters:
    max_velocity: 4.0
    ds: 0.15
    dt: 0.025
    horizon: 30
    F_init: 300.0
    F_max: 500.0
    F_min: -500.0
    mission: "autocross" 
    time_delay: 0.1
    T_max: 25.0
    T_min: -25.0
    angle_max: 0.436332157 #25 degrees
    angle_min: -0.436332157 #-25 degrees
    dynamic_ds: true #alvania

    #Model
    wb: 1590.0
    wd_front: 0.467
    CdA: 2.0
    ClA: 7.0
    p_air: 1.225
    h_cog: 0.27
    gr: 3.9
    Rw: 0.2
    m: 190.0
    g: 9.81
    Iz: 110.0
    N_rear: 2
    d_piston: 0.025
    R_disk_f: 0.079 
    R_disk_r: 0.0735
    mi_disk: 0.6
